CREATE TABLE Ticket
(
    id INTEGER AUTO_INCREMENT NOT NULL,
    movie VARCHAR(200) NOT NULL,
    number INT NOT NULL,
    firstname VARCHAR(200) NOT NULL,
    lastname VARCHAR(200) NOT NULL,
    phoneNb VARCHAR(8) NOT NULL,
    email VARCHAR(200) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Movie
(
    id INTEGER AUTO_INCREMENT NOT NULL,
    movie VARCHAR(200) NOT NULL,
    PRIMARY KEY (id)
);